### ISSUE TITLE
Skipper Shell: Uploading a package with same name and version that already exists should throw error 

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#317] opened 2017-11-10 04:57 UTC
Currently, using the `upload --path` command you can upload a package with the same `package-name` and `package-version` as one that already exists. Can cause some problems, mostly seems to default to first manifest given (working on proving this). 

Would be nice if `upload` threw an error if it gave an identical package already existed. 

Adding code to here:
https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/SkipperCommands.java 

Haven't tried the code yet, but the code from 154-169 should be reusable in the try on 318.

**Comment by ilayaperumalg** [comment] 2017-11-10 09:09
@AWeeks1 Thanks for reporting this and the suggestion!

One of the reasons not to throw the error was to allow updating the package that was already uploaded. Perhaps, we could add a property `--force` to enforce update of the upload and have the regular `upload` failed if it was already uploaded.

**Comment by AWeeks1** [comment] 2017-11-10 17:35
@ilayaperumalg 
I think that would be a good idea (adding the `--force` flag) in the same as normal cf pushes. If the package name + version exists it either overwrites or throws an `409 Conflict` or something.

Currently then if there are two packages with the same name + version (as below) which will it pick when you `install --[...]`. 

![image](https://user-images.githubusercontent.com/29645530/32670949-5c02bd94-c5fa-11e7-8397-bbf31649cf78.png)

**Comment by sabbyanandan** [comment] 2018-01-11 17:11
Relates to https://github.com/spring-cloud/spring-cloud-skipper/issues/417.

**Comment by sabbyanandan** [comment] 2018-01-11 17:27
As per the discussion, we won't implement `--force`, but we will implement `package delete ..` as an option.

**Comment by tzolov** [comment] 2018-01-12 11:44
Few questions we need to address before resolving this issue:
* Existing SCDF stream deployment implementation (http://bit.ly/2D5eLOt) always generates a new package, **uploads** it to Skipper and then installs it. That means that SCDF expects Skipper to allow packages (with same name and version) to be overwritten. If we disable it then we must re-implement the SCDF's deploy workflow too! 
* Is the package identified by `[name, version, repoId]` attributes or just `[name,version]`? Presuming the later means that the same [name,version] package can be uploaded to multiple repositories. Because of this the output of the `search` shell command should show also the `repoId` of the packages.
* We should implement the `package delete` in the scope of this (or dependent) issue so that by the time we disable package override we still have a mean to remove a package from a repository.
* if we decide to use `package delete` command for removing a package from a repository(s) perhaps we should rename the `upload` command into `package upload` as well?

**Comment by ilayaperumalg** [comment] 2018-01-12 12:08
> Existing SCDF stream deployment implementation (http://bit.ly/2D5eLOt) always generates a new package, uploads it to Skipper and then installs it. That means that SCDF expects Skipper to allow packages (with same name and version) to be overwritten. If we disable it then we must re-implement the SCDF's deploy workflow too!

Yeah, this is where `--force` option might be useful when uploading a package.

> Is the package identified by [name, version, repoId] attributes or just [name,version]? Presuming the later means that the same [name,version] package can be uploaded to multiple repositories. Because of this the output of the search shell command should show also the repoId of the packages.

Yeah, that's a good idea. We can use repo name there. On a related note, when the package is resolved for install/update, the package is retrieved from the repository that has the highest order (if package exists in multiple repositories).

> We should implement the package delete in the scope of this (or dependent) issue so that by the time we disable package override we still have a mean to remove a package from a repository.
if we decide to use package delete command for removing a package from a repository(s) perhaps we should rename the upload command into package upload as well?

+1 to have `package delete` in the scope of this issue.
On renaming `upload` -> `package upload`, we originally had it as `package upload` and it became `upload` for usage simplicity. I think we can discuss this to make it consistent.

**Comment by ilayaperumalg** [comment] 2018-01-12 12:09
In any case, to avoid any regressions that this change could probably bring now I would vote for not getting this in for RC1.

**Comment by markpollack** [comment] 2018-01-12 14:50
From the skipper side, this is a very nasty bug, feature gap, and we should fix it for RC.  

Overwriting a package, as long as there are no releases running with that package would make things easier on the SCDF side.

All three, name, version, and repoId make it unique.  Showing repoId to a user isn't that helpful, repoName would be better.  We should add repoName as well to the PackageMetadata class (vs querying later which is another story..)

We can group with under 'package' commands, doesn't seem like that implies we have to merge the two stories. Let's try to keep the scope as small as possible.

**Comment by tzolov** [comment] 2018-01-12 15:55
additional question: if the Package identity is (name, version, repoId) then why the equals/hashCode of the PackageMetadata include ALL properties?

**Comment by markpollack** [comment] 2018-01-12 19:49
1) package upload will fail if package name,verison,repoId are already.
   Equals method to include only these three fields.

**Comment by markpollack** [comment] 2018-01-12 19:56
Related issues #331 , #431

**Closed** 2018-01-13 18:40 UTC
Labels: in pr
