### ISSUE TITLE
Add integration tests in shell

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#85] opened 2017-09-18 02:48 UTC
e.g. added add/delete/list commands that call the Spring Data REST repository endpoints. The command should be exercised in an integration test.

This applies generally to all commands, but started here is a good first step.

**Comment by ilayaperumalg** [comment] 2017-09-18 04:46
This is the duplicate of #75

**Closed** 2017-09-25 01:41 UTC
Labels: duplicate
